### ISSUE TITLE
can't use mouse and right click to scroll through the map

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25edit#33]
hey there, 

is this a known bug? Its impossible to use mouse and right click to scroll through a map which has been loaded into the editor: 

![s25edit](https://user-images.githubusercontent.com/14232936/228437239-c1685a59-252f-4ff1-ad46-195201db8c47.png)

If its not a known bug yet, I can check older stable version if it was introduced with the recently introduced libsdl2 changes.

**Comment by Flamefire** [comment]
Works fine for me on Win10. So which system are you using? Also what is the screenshot supposed to show? I don't see anything wrong there, so what shall I look at?

**Comment by morganchristiansson** [comment]
I had same issue in s25client linux stable, but it's fixed in nightlies.
Not sure what the state was in 2023.
But with PR #37 the s25edit mouse scrolling works for me in Linux.

**Comment by stefson** [comment]
this was def not fixed in 230b1bb51961692f50f786e24de50be4d6a89046

**Comment by stefson** [comment]
so yes, I'm on https://github.com/Return-To-The-Roots/s25client/commit/230b1bb51961692f50f786e24de50be4d6a89046 and it is indeed not fixed.

**Comment by morganchristiansson** [comment]
This commit in not yet merged #37 https://github.com/Return-To-The-Roots/s25edit/pull/37/changes/0c7a57a76a94984d0e6b403711196a97901a2f8d aligns and syncs the scrolling with s25client.
You linked to s25client commit?
